---

# sudo: required

language: python
python:
  - "2.7"

services:
  - docker

before_install:
  - docker pull ubuntu:16.04
script:
  - pip install ansible
  - docker run -d --name xenial ubuntu:16.04
  # - ansible-playbook -i test/inventory --connection=docker --syntax-check --list-tasks test/test_docker.yml
  - ansible-playbook -i test/inventory --connection=docker --become -vvvv test/test_docker.yml
    # - >
    #     ansible-playbook -i test/inventory --connection=local --become -vvvv test/test.yml -u root
    #     | grep -q 'changed=0.*failed=0'
    #     && (echo 'Idempotence test: pass' && exit 0)
    #     || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
