---

sudo: required

language: python
  - "2.7.9"

services:
  - docker

before_install:
  - docker pull williamyeh/ansible:ubuntu16.04
  - docker run -d -p 127.0.0.1:80:4567 williamyeh/ansible:ubuntu16.04 /bin/sh -c "ansible --version"

install:
  - sudo apt-get install python-dev libffi-dev libssl-dev
  - pip install 'requests[security]' --upgrade ansible-lint

script:
   - ansible-lint tasks/main.yml
# before_script:
#   - pip install ansible-lint
# script:
  # - pip install ansible ansible-lint
  # - ansible --version
  # - ansible-lint tasks/main.yml
  # - ansible-playbook -i test/inventory --syntax-check --list-tasks test/test.yml
  # - ansible-playbook -i test/inventory --connection=local --become -vvvv test/test.yml -u root
  # - >
  #     ansible-playbook -i test/inventory --connection=local --become -vvvv test/test.yml -u root
  #     | grep -q 'changed=0.*failed=0'
  #     && (echo 'Idempotence test: pass' && exit 0)
  #     || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
